services:

  # ================== MKDocs
  mkdocs:
    container_name: mkdocs
    image: polinux/mkdocs
    restart: unless-stopped

    environment:
      LIVE_RELOAD_SUPPORT: 'true'
      ADD_MODULES: 'fontawesome-markdown mkdocs-git-revision-date-localized-plugin mkdocs-material'
      FAST_MODE: 'true'
      DOCS_DIRECTORY: '/mkdocs'

    ports:
      - "8000:8000"

    volumes:
      - mkdocs:/mkdocs 

volumes:
  mkdocs:                         
    driver_opts:
      type: none
      device: ~/docker/mkdocs/volume/mkdocs
      o: bind
