site_name: Carmelo-Proyect
site_author: Carmelo Molero Castillo

# Extensiones de Markdown
markdown_extensions:
   - admonition
   - codehilite
   - toc:
      permalink: true

# Tema y configuración
theme:
   name: "mkdocs"
   language: "es"
   color_mode: "dark"
   user_color_mode_toggle: true
   prev_next_buttons_location: "bottom"

# Navegación
nav:
   - Self-Hosting:
      - Duplicati: self-hosting/duplicati/duplicati.md
      - Homarr: self-hosting/homarr/homarr.md
      - Homebridge: self-hosting/homebridge/homebridge.md
      - Jellyfin: self-hosting/jellyfin/jellyfin.md
      - MkDocs: self-hosting/mkdocs/mkdocs.md
      - Nextcloud: self-hosting/nextcloud/nextcloud.md
      - PiHole: self-hosting/pihole/pihole.md
      - Plex: self-hosting/plex/plex.md
      - Portainer: self-hosting/portainer/portainer.md
      - Samba: self-hosting/samba/samba.md
      - Speedtest: self-hosting/speedtest/speedtest.md
      - StirlingPDF: self-hosting/stirling_pdf/stirlingpdf.md
      - Watchtower: self-hosting/watchtower/watchtower.md
      - WatchYourLAN: self-hosting/watchyourlan/watchyourlan.md
   - Docker:
      - Introducción: docker/introduccion.md
      - Imágenes: docker/imagenes.md
      - Contenedores: docker/contenedores.md
      - Volúmenes: docker/volumenes.md
      - Redes: docker/redes.md
      - Comandos útiles: docker/comandos.md
      - Optimización y troubleshooting: docker/troubleshooting.md
   - Linux:
      - Sistemas de archivos:
         - Restaurar particiones clonezilla: linux/sistemas-archivos/particiones/restaurar_particiones_clonezilla/restaurar_particiones_clonezilla.md
         - MHDDFS: linux/sistemas-archivos/mhddfs/mhddfs.md
      - Redes:
         - Guía DHCP: linux/redes/dhcp/dhcp.md
         - Guía SSH: linux/redes/ssh/ssh.md
   - Raspberry Pi:
      - Introducción: raspberrypi/raspberrypi.md
      - Instalación básica: raspberrypi/instalacion-basica/instalacion-basica.md
      - Utilidades: 
         - Añadir HDD externo: raspberrypi/utilidades/pi-hdd/pi-hdd.md
         - Flashear EEPROM: raspberrypi/utilidades/eeprom/eeprom.md
         - Instalar Docker: raspberrypi/utilidades/docker/docker.md
         - Reducir imagen MicroSD: raspberrypi/utilidades/microsd/microsd.md
      - Servidor NAS: raspberrypi/servidor-nas/servidor-nas.md
